$:
  vscode:
    - runner:
        cpus: 1
      services:
        - vscode
        - docker

.github-sync: &github-sync
  runner:
    cpus: 1
  env:
    GITHUB_REPO: https://github.com/Womsxd/MihoyoBBSTools.git
  stages:
    - name: sync
      script: |
        git remote set-url origin "${GITHUB_REPO}"
        git fetch origin --prune --tags --force
        git remote set-url origin "${CNB_REPO_URL_HTTPS}"
        git push --mirror origin --force


master:
  "crontab: 0 6 * * *": 
    - *github-sync
  web_trigger_sync: 
    - *github-sync
